image: node:18-alpine

# Cache les modules pour accélérer les prochains builds
cache:
  paths:
    - .npm/

pages:
  stage: deploy
  script:
    - npm ci --cache .npm --prefer-offline
    - npm run docs:build

    # VitePress génère par défaut dans .vitepress/dist
    # On déplace le contenu vers 'public' pour GitLab
    - rm -rf public
    - mv docs/.vitepress/dist public
  artifacts:
    paths:
      - public
  only:
    - main # Ou 'master' selon votre branche principale
